#!/usr/bin/env python
"""Generate a synthetic demo plot + a calibrated configs/plots.yaml.

The demo is fully synthetic (no third-party figure) so the HSV-marker pipeline runs
out of the box and the example is copyright-clean. Run from the package root:

    python tools/make_demo.py

It renders three coloured marker series (square / circle / triangle) with same-colour
dashed "fit" lines on a linear-T / log10-mole-fraction axis, then reads the exact axis
pixel positions back out of matplotlib's transforms to write the calibration.
"""
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG = os.path.join(PKG, "demo", "demo_plot.png")
CFG = os.path.join(PKG, "configs", "plots.yaml")
DPI = 100

# --- synthetic data: T(K) vs mole fraction, three species -------------------
# three non-overlapping bands so the synthetic markers stay cleanly separable
T = np.linspace(820, 1180, 10)
series = {
    "alpha": dict(color=(0.90, 0.0, 0.0), marker="s", y=2.0e-3 * (1 + 0.18 * np.cos((T - 820) / 90))),
    "gamma": dict(color=(0.0, 0.80, 0.0), marker="^", y=1.3e-4 * (1 + 0.30 * np.sin((T - 820) / 70))),
    "beta":  dict(color=(0.0, 0.0, 0.90), marker="o", y=5e-6 * 10 ** ((T - 820) / 360 * 1.0)),
}

fig, ax = plt.subplots(figsize=(6.4, 5.0), dpi=DPI)
for name, s in series.items():
    ax.semilogy(T, s["y"], linestyle="--", lw=1.5, color=s["color"], zorder=1)
    ax.semilogy(T, s["y"], linestyle="none", marker=s["marker"], ms=15,
                mfc=s["color"], mec=s["color"], label=name, zorder=2)
ax.set_xlim(800, 1200)
ax.set_ylim(1e-6, 1e-2)
ax.set_xlabel("T (K)")
ax.set_ylabel("mole fraction")
leg = ax.legend(loc="lower right", title="demo series")
fig.tight_layout()
fig.canvas.draw()

# --- read pixel calibration back out of matplotlib --------------------------
W, H = fig.canvas.get_width_height()


def img_px(x, y):                       # data -> image px (origin top-left)
    dx, dy = ax.transData.transform((x, y))
    return dx, H - dy


col800, _ = img_px(800, 1e-3)
col1200, _ = img_px(1200, 1e-3)
_, row_em2 = img_px(1000, 1e-2)         # mole fraction 1e-2 -> y_log0 = -2
_, row_em3 = img_px(1000, 1e-3)
bb = ax.get_window_extent()
box = [bb.x0, bb.x1, H - bb.y1, H - bb.y0]
lb = leg.get_window_extent()
legend = [lb.x0, lb.x1, H - lb.y1, H - lb.y0]

fig.savefig(IMG, dpi=DPI)
plt.close(fig)


def ints(v):                            # box/legend are pixel rectangles -> ints
    return [int(round(x)) for x in v]


cfg = f"""# Synthetic demo configuration generated by tools/make_demo.py (do not hand-edit;
# regenerate instead). Calibration is read straight from matplotlib's axis transforms.
image_dir: demo
out_dir: extracted

families:
  demo:
    species:
      alpha: {{ranges: [[0, 10, 110, 255, 90, 255], [170, 179, 110, 255, 90, 255]]}}   # red square
      beta:  {{ranges: [[108, 132, 110, 255, 90, 255]], shape: circle}}                 # blue circle
      gamma: {{ranges: [[45, 75, 110, 255, 90, 255]], shape: triangle}}                 # green triangle

plots:
  demo:
    family: demo
    image: demo_plot.png
    calib: {{x_p0: {col800:.2f}, x_k0: 800.0, x_span_K: 400.0,
            x_px_lo: {col800:.2f}, x_px_hi: {col1200:.2f},
            y0px: {row_em2:.2f}, y_log0: -2.0, y_pxPerDecade: {row_em3 - row_em2:.2f}}}
    box: {ints(box)}
    legend: {ints(legend)}
"""
with open(CFG, "w") as fh:
    fh.write(cfg)

print(f"wrote {IMG} ({W}x{H}) and {CFG}")
print(f"x: 800->{col800:.1f}px  1200->{col1200:.1f}px | "
      f"y: 1e-2->{row_em2:.1f}px  {row_em3 - row_em2:.1f}px/decade")
